pipeline:
    name: website
    identifier: website
    allowStageExecutions: false
    projectIdentifier: website
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: Github
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: ausworkload
                          namespace: default
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: dockerbuild
                                identifier: dockerbuild
                                spec:
                                    connectorRef: account.harnessImage
                                    repo: laurosg87/coffee-lab
                                    tags:
                                        - harness
                                failureStrategies: []
